import palette from './palette.json' with { type: 'json' };

/** 第二关：由 tools/image_to_art.py 生成 ART 后写入此文件。 */
const ART = [
  '..............KKKKKK..............',
  '............KKKRRRRKKK............',
  '............KRRRRRO.RK............',
  'KKKKK.......KRRRRROWRK............',
  'KYOOK.......KRRRRRRRRK............',
  'KKKYOKKKKKKWWWWWWWWWWWWKKKK.......',
  'KKYOKKKKWWWWWWWWWWWWWWWWWWKK......',
  '.KOKOKKOWWWWWWWWWWWWWWWWWWWKK.....',
  '.KKYKOWWWWRRRRORRWWWWWWWWWWWK.....',
  '..KKOWWWWWRRRRRRRROWWWWWWWWWKK....',
  '..KKOOWWWWWWRRRRR.WWWWWWWWWWKK....',
  '...KOOOWWWWWWWWWWWWWWWWWWWWWKK....',
  '...KKYOWWWWWWWWWWWWWWWWWWWWWKK....',
  '..KKKYOOWWMWWMMMMMMMMMWWMWWKKK....',
  '.KKMKOMMMM.WWMMMMMMMMMWMWWMMKKK...',
  'KKPMPPMPPPMMMPMMPPPPPPMMMMPMMGMMKK',
  'KPPPPMPMMPPPPMPPPPPPMPMPPPPMMMGMMK',
  'KPPPMPPPPMPPMPPPPPPPPMPPPPPMMGGGMK',
  'KPMPPPPPPPMPPMPPPPMMPPPPPPPMGGGGMK',
  'KMPPPPPPPMPPPPPPPMMPPPPPPPMGGGGMMK',
  'KKPPPPPPMPPPPPPPMMPPPPPPPMPMGGMMKK',
  'KCCCCBBBBBBGYYYYYYYYYYGBBBBBBCCCK.',
  'KCCCCBBBBBBBBYYYYYYYYBBBBBBBBCCCK.',
  'KKCCCBBBBBBBBBYYYYYYBBBBBBBBBCCKK.',
  '.KKCCCCBBBBBBBBBBBBBBBBBBBBCCCKK..',
  '..KKCCCCCCCCCCCCCCCCCCCCCCCCCKK...',
  '...KKCCCCCCCCCCCCCCCCCCCCCCCKK....',
  '...KKKKKKKKKKKCCCCKKKKKKKKKKK.....',
  '.......KKKKKKKCCCCKKKKKKKK........',
  '......KKCCCCCCCCCCCCCCCCCKK.......',
  '.....KKCCCCCCCCCCCCCCCCCCCKK......',
  '.....KKCCCCCCCCCCCCCCCCCCCKK......',
  '.....KKKCCCCCCCCCCCCCCCCCKKK......',
  '......KKKKKKKKKKKKKKKKKKKKK.......'
];

const QUEUE_ART = ['KRM', 'PCY', 'WOB'];

export default { art: ART, queueArt: QUEUE_ART, palette };
